import {
  Service,
  Transaction,
  User,
  Ad,
  Task,
  Advertiser,
  Campaign,
  WithdrawalRequest,
  Ticket,
  DashboardBanner,
  HomepageBanner,
  Broadcast,
  AdminSettings,
  PriceListItem,
  MaintenanceMode,
  TaskReview,
} from "./models";

export const mockServices: Service[] = [
  {
    id: "mock-service-1",
    name: "API Gateway",
    description: "Шлюз для микросервисной архитектуры",
    status: "active",
    url: "https://api.example.com",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "mock-service-2",
    name: "Auth Service",
    description: "Сервис аутентификации и авторизации",
    status: "active",
    url: "https://auth.example.com",
    createdAt: new Date("2024-02-01").toISOString(),
    updatedAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "mock-service-3",
    name: "ML Pipeline",
    description: "Пайплайн для обработки данных с AI",
    status: "deploying",
    url: undefined,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
];

export const mockUsers: User[] = [
  {
    id: "mock-user-1",
    email: "user@example.com",
    phone: "+71234567890",
    passwordHash:
      "dummyhash:dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy",
    verified: true,
    blocked: false,
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "mock-tx-1",
    userId: "mock-user-1",
    type: "earnings",
    amount: 1,
    description: "Просмотр рекламы — «Новый бренд кофе»",
    status: "completed",
    createdAt: new Date("2024-06-15T10:30:00Z").toISOString(),
  },
  {
    id: "mock-tx-2",
    userId: "mock-user-1",
    type: "earnings",
    amount: 1.2,
    description: "Просмотр рекламы — «Страховка онлайн»",
    status: "completed",
    createdAt: new Date("2024-06-15T09:15:00Z").toISOString(),
  },
  {
    id: "mock-tx-3",
    userId: "mock-user-1",
    type: "earnings",
    amount: 8.0,
    description: "Выполнение задания — YouTube: просмотр видео",
    status: "completed",
    createdAt: new Date("2024-06-14T18:45:00Z").toISOString(),
  },
  {
    id: "mock-tx-4",
    userId: "mock-user-1",
    type: "withdrawal",
    amount: -50.0,
    description: "Вывод на карту",
    status: "completed",
    createdAt: new Date("2024-06-13T14:20:00Z").toISOString(),
  },
  {
    id: "mock-tx-5",
    userId: "mock-user-1",
    type: "earnings",
    amount: 2.0,
    description: "Просмотр рекламы — «Мобильный банк»",
    status: "completed",
    createdAt: new Date("2024-06-13T11:00:00Z").toISOString(),
  },
  {
    id: "mock-tx-6",
    userId: "mock-user-1",
    type: "referral",
    amount: 10.0,
    description: "Реферальное вознаграждение за друга",
    status: "completed",
    createdAt: new Date("2024-06-12T08:00:00Z").toISOString(),
  },
  {
    id: "mock-tx-7",
    userId: "mock-user-1",
    type: "withdrawal",
    amount: -30.0,
    description: "Вывод на ЮMoney",
    status: "completed",
    createdAt: new Date("2024-06-10T16:30:00Z").toISOString(),
  },
  {
    id: "mock-tx-8",
    userId: "mock-user-1",
    type: "earnings",
    amount: 4.5,
    description: "Просмотр рекламы — «Фитнес-клуб»",
    status: "completed",
    createdAt: new Date("2024-06-10T10:00:00Z").toISOString(),
  },
  {
    id: "mock-tx-9",
    userId: "mock-user-1",
    type: "deposit",
    amount: 200.0,
    description: "Пополнение через Робокассу",
    status: "completed",
    createdAt: new Date("2024-06-17T12:00:00Z").toISOString(),
  },
  {
    id: "mock-tx-10",
    userId: "mock-user-1",
    type: "deposit",
    amount: 500.0,
    description: "Пополнение через ЮMoney",
    status: "completed",
    createdAt: new Date("2024-06-11T09:00:00Z").toISOString(),
  },
];

export const mockAds: Ad[] = [
  {
    id: "mock-ad-1",
    title: "Новый бренд кофе",
    description: "Попробуйте ароматный кофе премиум-класса",
    type: "video",
    mediaUrl: "https://example.com/ads/coffee.mp4",
    reward: 0.04,
    duration: 10,
    status: "active",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "mock-ad-2",
    title: "Страховка онлайн",
    description: "Оформите страховку за 5 минут",
    type: "banner",
    mediaUrl: "https://example.com/ads/insurance.jpg",
    reward: 0.04,
    duration: 12,
    status: "active",
    createdAt: new Date("2024-06-02").toISOString(),
    updatedAt: new Date("2024-06-02").toISOString(),
  },
  {
    id: "mock-ad-3",
    title: "Мобильный банк",
    description: "Удобный банк в вашем смартфоне",
    type: "video",
    mediaUrl: "https://example.com/ads/bank.mp4",
    reward: 0.05,
    duration: 15,
    status: "active",
    createdAt: new Date("2024-06-03").toISOString(),
    updatedAt: new Date("2024-06-03").toISOString(),
  },
  {
    id: "mock-ad-4",
    title: "Фитнес-клуб",
    description: "Первая тренировка бесплатно",
    type: "banner",
    mediaUrl: "https://example.com/ads/fitness.jpg",
    reward: 0.04,
    duration: 10,
    status: "active",
    createdAt: new Date("2024-06-04").toISOString(),
    updatedAt: new Date("2024-06-04").toISOString(),
  },
  {
    id: "mock-ad-5",
    title: "Скидка 30% на авиабилеты",
    description: "Путешествуйте с выгодой",
    type: "video",
    mediaUrl: "https://example.com/ads/flights.mp4",
    reward: 0.07,
    duration: 20,
    status: "active",
    createdAt: new Date("2024-06-05").toISOString(),
    updatedAt: new Date("2024-06-05").toISOString(),
  },
];

export const mockTasks: Task[] = [
  // Социальные задания (taskType: social)
  {
    id: "mock-task-1",
    title: "Посмотри видео на YouTube",
    description: "Посмотри новый ролик про криптовалюты до конца",
    platform: "youtube",
    actionType: "watch",
    taskType: "social",
    url: "https://youtube.com/watch?v=example1",
    reward: 2.0,
    status: "active",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "mock-task-2",
    title: "Поставь лайк на VK",
    description: "Поставь лайк посту сообщества и сделай репост",
    platform: "vk",
    actionType: "like",
    taskType: "social",
    url: "https://vk.com/wall-123456_789",
    reward: 1.5,
    status: "active",
    createdAt: new Date("2024-06-02").toISOString(),
    updatedAt: new Date("2024-06-02").toISOString(),
  },
  {
    id: "mock-task-3",
    title: "Подпишись на YouTube-канал",
    description: "Подпишись на YouTube-канал и посмотри шортс",
    platform: "youtube",
    actionType: "subscribe",
    taskType: "social",
    url: "https://youtube.com/@channel1",
    reward: 3.0,
    status: "active",
    createdAt: new Date("2024-06-03").toISOString(),
    updatedAt: new Date("2024-06-03").toISOString(),
  },
  {
    id: "mock-task-4",
    title: "Вступи в группу VK",
    description: "Вступи в группу и оставь комментарий под постом",
    platform: "vk",
    actionType: "subscribe",
    taskType: "social",
    url: "https://vk.com/club123456",
    reward: 2.5,
    status: "active",
    createdAt: new Date("2024-06-04").toISOString(),
    updatedAt: new Date("2024-06-04").toISOString(),
  },
  {
    id: "mock-task-5",
    title: "Посмотри видео на RuTube",
    description: "Посмотри видео до конца на RuTube",
    platform: "other",
    actionType: "watch",
    taskType: "social",
    url: "https://rutube.ru/video/example1",
    reward: 1.8,
    status: "active",
    createdAt: new Date("2024-06-05").toISOString(),
    updatedAt: new Date("2024-06-05").toISOString(),
  },
  // Подписки (taskType: subscription)
  {
    id: "mock-task-6",
    title: "Подпишись на Telegram-канал",
    description: "Подпишись на Telegram-канал про технологии и инновации",
    platform: "telegram",
    actionType: "subscribe",
    taskType: "subscription",
    url: "https://t.me/techchannel",
    reward: 2.0,
    status: "active",
    campaignId: "mock-campaign-6",
    createdAt: new Date("2024-06-06").toISOString(),
    updatedAt: new Date("2024-06-06").toISOString(),
  },
  {
    id: "mock-task-7",
    title: "Подпишись на YouTube-блогера",
    description: "Подпишись на YouTube-канал популярного блогера",
    platform: "youtube",
    actionType: "subscribe",
    taskType: "subscription",
    url: "https://youtube.com/@popularblogger",
    reward: 2.5,
    status: "active",
    createdAt: new Date("2024-06-07").toISOString(),
    updatedAt: new Date("2024-06-07").toISOString(),
  },
  {
    id: "mock-task-8",
    title: "Подпишись на Telegram про финансы",
    description: "Подпишись на канал с советами по финансам и инвестициям",
    platform: "telegram",
    actionType: "subscribe",
    taskType: "subscription",
    url: "https://t.me/financechannel",
    reward: 1.5,
    status: "active",
    createdAt: new Date("2024-06-08").toISOString(),
    updatedAt: new Date("2024-06-08").toISOString(),
  },
  // CPC — переходы по ссылкам (taskType: cpc)
  {
    id: "mock-task-9",
    title: "Перейди на сайт интернет-магазина",
    description: "Перейди по ссылке и ознакомься с ассортиментом",
    platform: "cpc",
    actionType: "cpc",
    taskType: "cpc",
    url: "https://example-shop.ru",
    reward: 0.5,
    status: "active",
    campaignId: "mock-campaign-3",
    createdAt: new Date("2024-06-09").toISOString(),
    updatedAt: new Date("2024-06-09").toISOString(),
  },
  {
    id: "mock-task-10",
    title: "Посмотри лендинг нового сервиса",
    description: "Перейди на лендинг и узнай о преимуществах сервиса",
    platform: "cpc",
    actionType: "cpc",
    taskType: "cpc",
    url: "https://example-service.ru",
    reward: 0.3,
    status: "active",
    createdAt: new Date("2024-06-10").toISOString(),
    updatedAt: new Date("2024-06-10").toISOString(),
  },
  {
    id: "mock-task-11",
    title: "Оцени новый онлайн-курс",
    description: "Перейди на страницу курса и посмотри программу",
    platform: "cpc",
    actionType: "cpc",
    taskType: "cpc",
    url: "https://example-course.ru",
    reward: 0.7,
    status: "active",
    createdAt: new Date("2024-06-11").toISOString(),
    updatedAt: new Date("2024-06-11").toISOString(),
  },
  // Установка приложений (taskType: app_install)
  {
    id: "mock-task-12",
    title: "Установи мобильное приложение",
    description: "Скачай и установи приложение для заметок",
    platform: "app",
    actionType: "install",
    taskType: "app_install",
    url: "https://play.google.com/store/apps/details?id=com.example",
    reward: 5.0,
    status: "active",
    campaignId: "mock-campaign-5",
    createdAt: new Date("2024-06-12").toISOString(),
    updatedAt: new Date("2024-06-12").toISOString(),
  },
  {
    id: "mock-task-13",
    title: "Запусти игру на телефоне",
    description: "Установи игру и пройди обучение",
    platform: "app",
    actionType: "install",
    taskType: "app_install",
    url: "https://apps.apple.com/app/example-game",
    reward: 8.0,
    status: "active",
    createdAt: new Date("2024-06-13").toISOString(),
    updatedAt: new Date("2024-06-13").toISOString(),
  },
  // Опросы (taskType: survey)
  {
    id: "mock-task-14",
    title: "Пройди опрос про мобильные сервисы",
    description: "Ответь на 5 вопросов о мобильных приложениях",
    platform: "survey",
    actionType: "survey",
    taskType: "survey",
    url: "https://example-survey.com/survey1",
    reward: 3.0,
    status: "active",
    campaignId: "mock-campaign-4",
    createdAt: new Date("2024-06-14").toISOString(),
    updatedAt: new Date("2024-06-14").toISOString(),
  },
  {
    id: "mock-task-15",
    title: "Заполни анкету о путешествиях",
    description: "Расскажи о своих предпочтениях в путешествиях",
    platform: "survey",
    actionType: "survey",
    taskType: "survey",
    url: "https://example-survey.com/survey2",
    reward: 4.0,
    status: "active",
    campaignId: "mock-campaign-4",
    createdAt: new Date("2024-06-15").toISOString(),
    updatedAt: new Date("2024-06-15").toISOString(),
  },
];

export const mockAdvertisers: Advertiser[] = [
  {
    id: "mock-advertiser-1",
    companyName: "ООО Реклама Про",
    email: "advertiser@example.com",
    phone: "+71234567891",
    passwordHash:
      "dummyhash:dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy",
    balance: 15000,
    referredBy: "mock-user-1",
    createdAt: new Date("2024-05-01").toISOString(),
    updatedAt: new Date("2024-05-01").toISOString(),
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "mock-campaign-1",
    advertiserId: "mock-advertiser-1",
    title: "Новый бренд кофе",
    description: "Продвижение премиального кофе",
    type: "video",
    mediaUrl: "https://example.com/ads/coffee.mp4",
    budget: 5000,
    duration: 10,
    costPerView: 0.5,
    status: "active",
    views: 1200,
    clicks: 0,
    spend: 1200,
    completions: 0,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "mock-campaign-2",
    advertiserId: "mock-advertiser-1",
    title: "Страховка онлайн",
    description: "Баннерная кампания",
    type: "banner",
    mediaUrl: "https://example.com/ads/insurance.jpg",
    budget: 6000,
    duration: 12,
    costPerView: 0.6,
    status: "active",
    views: 3000,
    clicks: 0,
    spend: 3600,
    completions: 0,
    createdAt: new Date("2024-06-05").toISOString(),
    updatedAt: new Date("2024-06-05").toISOString(),
  },
  {
    id: "mock-campaign-3",
    advertiserId: "mock-advertiser-1",
    title: "Переход на сайт магазина",
    description: "CPC-кампания для интернет-магазина",
    type: "cpc",
    targetUrl: "https://example-shop.ru",
    taskDescription: "Перейти на сайт и ознакомиться с ассортиментом",
    budget: 1500,
    duration: 10,
    costPerView: 0.5,
    status: "active",
    views: 0,
    clicks: 450,
    spend: 450,
    completions: 120,
    createdAt: new Date("2024-06-10").toISOString(),
    updatedAt: new Date("2024-06-10").toISOString(),
  },
  {
    id: "mock-campaign-4",
    advertiserId: "mock-advertiser-1",
    title: "Опрос о мобильных сервисах",
    description: "Анкетирование пользователей",
    type: "survey",
    targetUrl: "https://example-survey.com/survey1",
    taskDescription: "Пройдите опрос из 5 вопросов о мобильных приложениях",
    budget: 2000,
    duration: 10,
    costPerView: 0.5,
    status: "active",
    views: 0,
    clicks: 120,
    spend: 120,
    completions: 50,
    createdAt: new Date("2024-06-12").toISOString(),
    updatedAt: new Date("2024-06-12").toISOString(),
  },
  {
    id: "mock-campaign-5",
    advertiserId: "mock-advertiser-1",
    title: "Установка приложения",
    description: "Продвижение мобильного приложения",
    type: "app_install",
    targetUrl: "https://play.google.com/store/apps/details?id=com.example",
    taskDescription: "Установите приложение и зарегистрируйтесь",
    budget: 5000,
    duration: 10,
    costPerView: 0.5,
    status: "active",
    views: 0,
    clicks: 200,
    spend: 200,
    completions: 85,
    createdAt: new Date("2024-06-15").toISOString(),
    updatedAt: new Date("2024-06-15").toISOString(),
  },
  {
    id: "mock-campaign-6",
    advertiserId: "mock-advertiser-1",
    title: "Подписка на Telegram-канал",
    description: "Привлечение подписчиков",
    type: "subscription",
    targetUrl: "https://t.me/techchannel",
    taskDescription: "Подпишитесь на Telegram-канал про технологии",
    budget: 1000,
    duration: 10,
    costPerView: 0.5,
    status: "paused",
    views: 0,
    clicks: 80,
    spend: 80,
    completions: 35,
    createdAt: new Date("2024-06-18").toISOString(),
    updatedAt: new Date("2024-06-18").toISOString(),
  },
];

export const mockWithdrawalRequests: WithdrawalRequest[] = [
  {
    id: "mock-wd-1",
    userId: "mock-user-1",
    amount: 500,
    method: "card",
    recipient: "2200 **** **** 1234",
    status: "pending",
    createdAt: new Date("2024-06-16T10:00:00Z").toISOString(),
  },
  {
    id: "mock-wd-2",
    userId: "mock-user-1",
    amount: 1000,
    method: "yoomoney",
    recipient: "4100**********5678",
    status: "approved",
    createdAt: new Date("2024-06-14T15:30:00Z").toISOString(),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "mock-ticket-1",
    userId: "mock-user-1",
    subject: "Не начислились деньги за просмотр",
    message:
      "Посмотрел 3 рекламы, а баланс не изменился. Проверьте пожалуйста.",
    status: "open",
    createdAt: new Date("2024-06-16T10:30:00Z").toISOString(),
    updatedAt: new Date("2024-06-16T10:30:00Z").toISOString(),
  },
  {
    id: "mock-ticket-2",
    userId: "mock-user-1",
    subject: "Вопрос по выводу средств",
    message: "Как долго обрабатывается заявка на вывод?",
    status: "closed",
    adminResponse: "Обычно заявка обрабатывается в течение 24 часов.",
    createdAt: new Date("2024-06-15T14:00:00Z").toISOString(),
    updatedAt: new Date("2024-06-15T16:30:00Z").toISOString(),
  },
];

export const mockDashboardBanners: DashboardBanner[] = [
  {
    id: "mock-db-1",
    userId: "mock-user-1",
    imageUrl: "https://picsum.photos/800/200?random=1",
    targetUrl: "https://example.com/promo1",
    status: "active",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "mock-db-2",
    userId: "mock-user-2",
    imageUrl: "https://picsum.photos/800/200?random=2",
    targetUrl: "https://example.com/promo2",
    status: "active",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "mock-db-3",
    userId: "mock-user-3",
    imageUrl: "https://picsum.photos/800/200?random=3",
    targetUrl: "https://example.com/promo3",
    status: "active",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
];

export const mockBroadcasts: Broadcast[] = [
  {
    id: "mock-broadcast-1",
    title: "Важное объявление",
    message:
      "Уважаемые пользователи! На платформе обновлены условия начисления за просмотр рекламы. Теперь максимальный дневной лимит составляет 30 просмотров.",
    createdAt: new Date().toISOString(),
  },
];

export const mockAdminSettings: AdminSettings = {
  id: "global",
  minCostPerView: 1,
  minViews: 1000,
  updatedAt: new Date().toISOString(),
};

export const mockPriceList: PriceListItem[] = [
  {
    id: "youtube-views",
    name: "YouTube просмотры",
    description: "Просмотры видео на YouTube",
    price: 120,
    unit: "1000",
    category: "youtube",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "telegram-subscribers",
    name: "Telegram подписчики",
    description: "Подписчики Telegram канала",
    price: 8,
    unit: "шт",
    category: "telegram",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "instagram-likes",
    name: "Instagram лайки",
    description: "Лайки на публикации в Instagram",
    price: 200,
    unit: "1000",
    category: "instagram",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vk-views",
    name: "VK просмотры",
    description: "Просмотры видео в VK",
    price: 100,
    unit: "1000",
    category: "vk",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tiktok-views",
    name: "TikTok просмотры",
    description: "Просмотры видео в TikTok",
    price: 150,
    unit: "1000",
    category: "tiktok",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "youtube-subscribers",
    name: "YouTube подписчики",
    description: "Подписчики YouTube канала",
    price: 400,
    unit: "1000",
    category: "youtube",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "telegram-views",
    name: "Telegram просмотры",
    description: "Просмотры записей в Telegram",
    price: 6,
    unit: "1000",
    category: "telegram",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vk-subscribers",
    name: "VK подписчики",
    description: "Подписчики сообщества VK",
    price: 250,
    unit: "1000",
    category: "vk",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "instagram-subscribers",
    name: "Instagram подписчики",
    description: "Подписчики Instagram аккаунта",
    price: 500,
    unit: "1000",
    category: "instagram",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "youtube-likes",
    name: "YouTube лайки",
    description: "Лайки на видео YouTube",
    price: 300,
    unit: "1000",
    category: "youtube",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vk-likes",
    name: "VK лайки",
    description: "Лайки на записи VK",
    price: 150,
    unit: "1000",
    category: "vk",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tiktok-subscribers",
    name: "TikTok подписчики",
    description: "Подписчики TikTok аккаунта",
    price: 600,
    unit: "1000",
    category: "tiktok",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tiktok-likes",
    name: "TikTok лайки",
    description: "Лайки на видео TikTok",
    price: 250,
    unit: "1000",
    category: "tiktok",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "youtube-comments",
    name: "YouTube комментарии",
    description: "Комментарии под видео YouTube",
    price: 500,
    unit: "1000",
    category: "youtube",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vk-reposts",
    name: "VK репосты",
    description: "Репосты записей VK",
    price: 400,
    unit: "1000",
    category: "vk",
    updatedAt: new Date().toISOString(),
  },
];

export const mockMaintenanceMode: MaintenanceMode = {
  id: "global",
  enabled: false,
  message:
    "Платформа на техническом обслуживании. Приносим извинения за неудобства.",
  updatedAt: new Date().toISOString(),
};

export const mockTaskReviews: TaskReview[] = [
  {
    id: "mock-review-1",
    taskId: "mock-task-1",
    userId: "mock-user-1",
    advertiserId: "mock-advertiser-1",
    campaignId: undefined,
    reward: 2.0,
    status: "pending",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    expiresAt: new Date(Date.now() + 2 * 86400000).toISOString(),
    taskTitle: "Посмотри видео на YouTube",
  },
  {
    id: "mock-review-2",
    taskId: "mock-task-9",
    userId: "mock-user-1",
    advertiserId: "mock-advertiser-1",
    campaignId: "mock-campaign-3",
    reward: 0.5,
    status: "approved",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    reviewedAt: new Date(Date.now() - 86400000).toISOString(),
    taskTitle: "Перейди на сайт интернет-магазина",
  },
  {
    id: "mock-review-3",
    taskId: "mock-task-12",
    userId: "mock-user-1",
    advertiserId: "mock-advertiser-1",
    campaignId: "mock-campaign-5",
    reward: 5.0,
    status: "pending",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 3 * 86400000).toISOString(),
    taskTitle: "Установи мобильное приложение",
  },
];

export const mockHomepageBanners: HomepageBanner[] = [
  {
    id: "mock-hp-banner-1",
    userId: "mock-user-1",
    imageUrl: "https://picsum.photos/1200/200?random=10",
    targetUrl: "https://example.com/promo1",
    status: "active",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "mock-hp-banner-2",
    userId: "mock-user-2",
    imageUrl: "https://picsum.photos/1200/200?random=11",
    targetUrl: "https://example.com/promo2",
    status: "active",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "mock-hp-banner-3",
    userId: "mock-user-3",
    imageUrl: "https://picsum.photos/1200/200?random=12",
    targetUrl: "https://example.com/promo3",
    status: "active",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
];
